import { localAccountsEnabled } from "../auth/AuthConfig";
import type { LocalMatchReward } from "./LocalEconomy";
import { logger } from "./Logger";
import { ServerEnv } from "./ServerEnv";

/** Internal credential is generated by the master and inherited only by workers. */
export async function sendLocalMatchReward(
  match: LocalMatchReward,
): Promise<Record<string, number> | null> {
  if (!localAccountsEnabled() || !process.env.LOCAL_REWARD_KEY) return null;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const response = await fetch(
        `${ServerEnv.accountApiBase()}/internal/match-rewards`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-Local-Reward-Key": process.env.LOCAL_REWARD_KEY,
          },
          body: JSON.stringify(match),
          signal: AbortSignal.timeout(5000),
        },
      );
      if (response.ok) {
        const body = (await response.json().catch(() => null)) as {
          awards?: unknown;
        } | null;
        if (
          body !== null &&
          typeof body.awards === "object" &&
          body.awards !== null &&
          Object.values(body.awards).every(
            (amount) => Number.isSafeInteger(amount) && Number(amount) > 0,
          )
        ) {
          return body.awards as Record<string, number>;
        }
        return null;
      }
      if (response.status < 500) break;
    } catch {
      /* A retry is safe: the account service deduplicates game IDs. */
    }
  }
  logger.error("Unable to save local Caps rewards", { gameID: match.gameId });
  return null;
}
